# Generated by Django 5.1 on 2025-04-10 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CachedCountry",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("sendcloud_id", models.PositiveIntegerField()),
                ("name", models.CharField(max_length=255)),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("iso_2", models.CharField(max_length=2)),
                ("iso_3", models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name="CachedShippingMethod",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("sendcloud_id", models.PositiveIntegerField()),
                ("name", models.CharField(max_length=255)),
                ("carrier", models.CharField(max_length=255)),
                ("min_weight", models.DecimalField(decimal_places=3, max_digits=10)),
                ("max_weight", models.DecimalField(decimal_places=3, max_digits=10)),
                ("service_point_input", models.CharField(max_length=10)),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("countries", models.ManyToManyField(to="sendcloud.cachedcountry")),
            ],
        ),
    ]
