services:
  database:
    image: postgres:13.3-alpine
    restart: unless-stopped
    networks:
      - db
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: mode_groothandel
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: mode_groothandel
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "mode_groothandel"]
      interval: 10s
      timeout: 5s
      retries: 5

  web:
    build: .
    image: ghcr.io/kioui/mode-groothandel-synchronizer:latest
    restart: unless-stopped
    networks:
      - web
      - db
    expose:
      - "80"
    depends_on:
      - database
    volumes:
      - media:/media
      - cache:/app/cache
      - static:/static
    environment:
      POSTGRES_USER: mode_groothandel
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: mode_groothandel
      POSTGRES_HOST: database
      POSTGRES_PORT: 5432
      DJANGO_SECRET_KEY: ${DJANGO_SECRET_KEY}
      DJANGO_ALLOWED_HOSTS: synchronize.larsvanrhijn.nl,synchronize.mode-groothandel.nl
      SENTRY_DSN: ${SENTRY_DSN}

    healthcheck:
      test: ["CMD", "python", "manage.py", "check"]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  web:
    external: true
    name: external_web
  db:

volumes:
  db-data:
  media:
  cache:
