# Generated by Django 5.0.6 on 2024-06-08 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("invoices", "0002_alter_invoice_snelstart_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invoice",
            name="snelstart_id",
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
