# Generated by Django 5.0.6 on 2024-06-17 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PickTicket",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("uphance_id", models.IntegerField(unique=True)),
                ("sendcloud_id", models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ("shipment_number", models.IntegerField()),
                ("order_id", models.IntegerField()),
                ("sale_id", models.IntegerField()),
                ("shipped", models.BooleanField()),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
