# Generated by Django 5.1 on 2024-08-13 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pick_tickets", "0002_remove_pickticket_shipped"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pickticket",
            name="order_id",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="pickticket",
            name="sale_id",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="pickticket",
            name="shipment_number",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
