# Generated by Django 5.0.6 on 2024-06-15 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("uphance_id", models.IntegerField(unique=True)),
                ("snelstart_id", models.IntegerField(blank=True, null=True, unique=True)),
                ("uphance_name", models.CharField(max_length=255)),
                ("snelstart_name", models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
