# Generated by Django 5.0.6 on 2024-06-17 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="snelstart_id",
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
