# Generated by Django 5.2 on 2025-04-12 07:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("sendcloud", "0001_initial"),
        ("snelstart", "0002_cachedland_uphance_country_code"),
    ]

    operations = [
        migrations.CreateModel(
            name="Country",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "country_code",
                    models.CharField(help_text="Country code as known in Uphance.", max_length=10, unique=True),
                ),
                (
                    "mapped_country_code_in_snelstart",
                    models.ForeignKey(
                        blank=True,
                        help_text="Sometimes, a country code in Snelstart is not the same as a country code in Uphance. This field can be set if that is the case and the synchronisation tool can not map it automatically.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="snelstart.cachedland",
                    ),
                ),
                (
                    "mapped_shipping_method_for_pick_tickets",
                    models.ForeignKey(
                        blank=True,
                        help_text="Shipping method for pick tickets going to this country. If this is unset, the pick tickets will use the default shipping method.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="sendcloud.cachedshippingmethod",
                    ),
                ),
            ],
        ),
    ]
