# Generated by Django 5.2 on 2025-05-14 08:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("uphance", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CachedChannel",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("channel_id", models.PositiveIntegerField(unique=True)),
                ("name", models.CharField(max_length=255)),
                ("currency", models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name="ChannelMapping",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "channel",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="uphance.cachedchannel"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TaxMapping",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("tax_amount", models.FloatField(unique=True)),
                ("grootboekcode", models.UUIDField()),
                ("grootboekcode_shipping", models.UUIDField()),
                (
                    "channel_mapping",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="uphance.channelmapping"),
                ),
            ],
            options={
                "unique_together": {("channel_mapping", "tax_amount")},
            },
        ),
    ]
