# Generated by Django 5.2 on 2025-05-14 08:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("uphance", "0002_cachedchannel_channelmapping_taxmapping"),
    ]

    operations = [
        migrations.AlterField(
            model_name="channelmapping",
            name="channel",
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to="uphance.cachedchannel"),
        ),
        migrations.AlterField(
            model_name="taxmapping",
            name="tax_amount",
            field=models.FloatField(),
        ),
    ]
