# Generated by Django 5.2 on 2025-05-14 17:15
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("uphance", "0003_alter_channelmapping_channel_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="taxmapping",
            name="tax_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
