# Generated by Django 5.2 on 2025-05-14 17:20
import pytz
from datetime import datetime
from django.conf import settings
from django.db import migrations, models


def add_tax_name(apps, schema_editor):
    TaxMapping = apps.get_model("uphance", "TaxMapping")
    CachedBtwTarief = apps.get_model("snelstart", "CachedBtwTarief")

    timezone = pytz.timezone(settings.TIME_ZONE)
    now = timezone.localize(datetime.now())

    for tax_mapping in TaxMapping.objects.all():
        tax_name = CachedBtwTarief.objects.get(
            datum_vanaf__lte=now, datum_tot_en_met__gt=now, btw_percentage=tax_mapping.tax_amount
        )
        tax_mapping.tax_name = tax_name
        tax_mapping.save()


class Migration(migrations.Migration):

    dependencies = [
        ("uphance", "0004_taxmapping_tax_name"),
    ]

    operations = [
        migrations.RunPython(
            migrations.RunPython.noop,
            add_tax_name,
        ),
        migrations.AlterField(
            model_name="taxmapping",
            name="tax_name",
            field=models.CharField(max_length=100),
        ),
    ]
