# Generated by Django 5.0.6 on 2024-06-08 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CachedGrootboek",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("modified_on", models.DateTimeField()),
                ("omschrijving", models.CharField(max_length=200)),
                ("kostenplaats_verplicht", models.BooleanField()),
                ("rekening_code", models.CharField(max_length=100)),
                ("nonactief", models.BooleanField()),
                ("nummer", models.IntegerField()),
                ("grootboekfunctie", models.CharField(max_length=100)),
                ("grootboek_rubriek", models.CharField(max_length=100)),
                ("vat_rate_code", models.CharField(blank=True, max_length=100, null=True)),
                ("snelstart_id", models.UUIDField(unique=True)),
                ("uri", models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="CachedLand",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("naam", models.CharField(max_length=100)),
                ("landcode_iso", models.CharField(blank=True, max_length=100, null=True)),
                ("landcode", models.CharField(max_length=100)),
                ("snelstart_id", models.UUIDField(unique=True)),
                ("uri", models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="TaxMapping",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100, unique=True)),
                ("tax_amount", models.FloatField(unique=True)),
                ("grootboekcode", models.UUIDField()),
                ("grootboekcode_shipping", models.UUIDField()),
            ],
        ),
        migrations.CreateModel(
            name="CachedBtwTarief",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("btw_soort", models.CharField(max_length=100)),
                ("btw_percentage", models.FloatField()),
                ("datum_vanaf", models.DateTimeField()),
                ("datum_tot_en_met", models.DateTimeField()),
            ],
            options={
                "unique_together": {("btw_soort", "datum_vanaf")},
            },
        ),
    ]
