# Generated by Django 5.0.4 on 2024-05-09 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("snelstart", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CachedLand",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("naam", models.CharField(max_length=100)),
                ("landcode_iso", models.CharField(blank=True, max_length=100, null=True)),
                ("landcode", models.CharField(max_length=100)),
                ("snelstart_id", models.UUIDField(unique=True)),
                ("uri", models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name="taxmapping",
            name="name",
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name="taxmapping",
            name="tax_amount",
            field=models.FloatField(unique=True),
        ),
        migrations.AlterUniqueTogether(
            name="cachedbtwtarief",
            unique_together={("btw_soort", "datum_vanaf")},
        ),
    ]
