# Generated by Django 5.0.6 on 2024-08-07 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("snelstart", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="cachedland",
            name="uphance_country_code",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
