# Generated by Django 5.2 on 2025-04-12 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("snelstart", "0002_cachedland_uphance_country_code"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cachedland",
            name="uphance_country_code",
        ),
    ]
