# Generated by Django 5.2 on 2025-05-13 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("snelstart", "0003_remove_cachedland_uphance_country_code"),
    ]

    operations = [
        migrations.DeleteModel(
            name="TaxMapping",
        ),
    ]
