# Generated by Django 5.0.6 on 2024-06-08 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CreditNote",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("uphance_id", models.IntegerField(unique=True)),
                ("snelstart_id", models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ("credit_note_number", models.CharField(max_length=100)),
                ("credit_note_total", models.DecimalField(decimal_places=2, max_digits=10)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
